name: First sechedule action
on:
  schedule:
  - cron: "*/5 * * * 1-5"
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: From Monday to Friday
        run: echo "This is a schedule workflow test"
